---
title: "R Notebook"
output: html_notebook
---


```{r}
library(readr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(stringr)
```

### Segundo
```{r}
INICIO_SEGUNDA_SEMESTRE <- as.Date("01/07/2021", format="%d/%m/%Y")
# No tiene ID persona
# https://www.datosabiertos.gob.pe/dataset/informaci%C3%B3n-de-fallecidos-del-sistema-nacional-de-defunciones-ministerio-de-salud/resource
# https://cloud.minsa.gob.pe/s/nqF2irNbFomCLaa/download


# Si tiene ID persona
# https://www.datosabiertos.gob.pe/dataset/sinadef-certificado-defunciones

sinadef <- read_csv("2022_01_07_TB_SINADEF/TB_SINADEF.csv", col_types = cols(.default = col_character())) %>% 
    mutate(FECHA=as.Date(FECHA, "%m/%d/%Y"))


# https://www.datosabiertos.gob.pe/dataset/fallecidos-por-covid-19-ministerio-de-salud-minsa/resource/4b7636f3-5f0c-4404-8526
# https://cloud.minsa.gob.pe/s/xJ2LQ3QyRW38Pe5/download
sinadef_solo_covid <- read_delim("2022_01_07_fallecidos_covid_sinadef.csv", delim = ";") %>% 
        mutate(
            FECHA_FALLECIMIENTO = as.Date(as.character(FECHA_FALLECIMIENTO), "%Y%m%d"),
            ano = year(FECHA_FALLECIMIENTO)
        )

cdc <- 
    read_csv("2022_01_06_TB_FALLECIDO_HOSP_VAC.csv") %>% 
    mutate_at(vars(contains("fecha")), function(x){ as.Date(x, format="%d/%m/%Y") }) %>% 
    mutate(semana_muerte = paste0(year(fecha_fallecimiento), "|", str_pad(week(fecha_fallecimiento), 2, pad="0")))



```
Pense cruzar por vacuna, pero la data CDC ya incluye los muertos con criterio SINADEF
```{r}
# Data tarda demasiado en cargar, y en convertir la fecha
# Me interesa saber si los muertos eran no vacunados
# Asi que hay que cruzar con SINADEF y quedarnos con ese pedazo
# vacunas <- read_csv("vacunas_covid.csv") 
# write_rds(vacunas, "vacunas.rds")
# filter(vacunas, DOSIS > 2) %>% select(-)
# %>% 
#     mutate(fecha_vacunacion = as.Date(as.character(FECHA_VACUNACION), format = "%Y%m%d")) 
# vacunas %>% anti_join(sinadef %>% mutate(ID_PERSONA=as.integer(ID_PERSONA)), by = c("UUID"="ID_PERSONA"))
```


Ojo: diferenciar del SINADEF completo vs el SINADEF parcial-COVID


```{r}
muertos_covid_segundo_semestre <- nrow(
    filter(sinadef_solo_covid, FECHA_FALLECIMIENTO >= INICIO_SEGUNDA_SEMESTRE, year(FECHA_FALLECIMIENTO) == 2021)
)

muertos_covid_cdc_segundo_semestre <- nrow(
    filter(cdc, fecha_fallecimiento >= INICIO_SEGUNDA_SEMESTRE, year(fecha_fallecimiento) == 2021)
)

muertos_covid_cdc_segundo_semestre_vacunados <- nrow(
    filter(cdc, fecha_fallecimiento >= INICIO_SEGUNDA_SEMESTRE, year(fecha_fallecimiento) == 2021, flag_vacuna >=2)
)
    
muertos_toda_causa <- nrow(
    filter(sinadef, FECHA >= INICIO_SEGUNDA_SEMESTRE, year(FECHA) == 2021)
)




list(
    "muertos segundo semestre, toda causa"= muertos_toda_causa    ,
    "muertos segundo semestre, covid" = muertos_covid_segundo_semestre,
    "muertos segundo semestre, en CDC" = muertos_covid_cdc_segundo_semestre,
    'muertos CDC, vacunados'=muertos_covid_cdc_segundo_semestre_vacunados
)

```


```{r}
(muertos_toda_causa - muertos_covid_cdc_segundo_semestre_vacunados)/ muertos_toda_causa
```

```{r}
cdc %>% 
    filter(
        fecha_fallecimiento > INICIO_SEGUNDA_SEMESTRE,
        year(fecha_fallecimiento) == 2021
    ) %>% 
    count(flag_vacuna) %>% 
    mutate(n / muertos_covid_segundo_semestre)
```

34% de los muertos por Covid tenian las 2 vacunas
52% eran no vacunados


Cevallos se refirio a muertos por toda causa...


